FROM golang:1.23.8-alpine AS builder

WORKDIR /app
COPY . .
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod init my-go-app && \
  go mod tidy && \
  CGO_ENABLED=0 GOOS=linux go build -o my-go-app .

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/my-go-app .
EXPOSE 8088

CMD ["./my-go-app"]
